[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32 @ ~6.5.0
board = esp32doit-devkit-v1
framework = arduino

; Seri haberlesme hizi
monitor_speed = 115200
upload_speed = 921600

; Flash bellek tablosu (1.4MB App, 1.4MB OTA, 1.1MB LittleFS)
board_build.partitions = partitions.csv
board_build.filesystem = littlefs

; Derleme bayraklari:
; - NAPT (Network Address Port Translation) aktiflestirme
; - lwIP IP forwarding
; - mbedTLS bellek optimizasyonu (RAM tasarrufu)
build_flags = 
    -DIP_NAPT=1
    -DCONFIG_LWIP_IP_FORWARD=1
    -DCONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=4096
    -DCONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
    -DCORE_DEBUG_LEVEL=3

; Bagimli kutuphaneler
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
