#pragma once

// Otomatik uretilen ECC (secp256r1) SSL Sertifikasi ve Gizli Anahtari
// CN: denemesitem.com
// SAN: DNS:denemesitem.com, DNS:www.denemesitem.com, IP:192.168.4.1

const char SERVER_CERT_PEM[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIBwTCCAWigAwIBAgIUI4/qZM68WTaux+VJz4phSiaMNYIwCgYIKoZIzj0EAwIw
GjEYMBYGA1UEAwwPZGVuZW1lc2l0ZW0uY29tMB4XDTI2MTAwNjEyMzQzM1oXDTM2
MTAwMzEyMzQzM1owGjEYMBYGA1UEAwwPZGVuZW1lc2l0ZW0uY29tMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEYh38xlFNikF2S8IW39LsAl/gX0brW3aNjpWwvX6s
q9pWfBTPtgkBRNKs2/+eA/PN6wpipGsIw0df1LEB1EBuQqOBizCBiDAdBgNVHQ4E
FgQUWwZwCj9OLkZ+Rik/p4Jr2oWh5uswHwYDVR0jBBgwFoAUWwZwCj9OLkZ+Rik/
p4Jr2oWh5uswDwYDVR0TAQH/BAUwAwEB/zA1BgNVHREELjAsgg9kZW5lbWVzaXRl
bS5jb22CE3d3dy5kZW5lbWVzaXRlbS5jb22HBMCoBAEwCgYIKoZIzj0EAwIDRwAw
RAIgGfolHAWMipCZftYMstXcnV0WZ6mvY4P0GzOAtTHjYbMCIFvV6FKfNKTFFoNx
WOIUoX3e4HiDCbzu8X5t5HV9icFd
-----END CERTIFICATE-----

)EOF";

const char SERVER_KEY_PEM[] PROGMEM = R"EOF(
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgmPxw6HbFL741CXzp
/UI/upcbZ+1IMfbnVW3A7FbgIJOhRANCAARiHfzGUU2KQXZLwhbf0uwCX+BfRutb
do2OlbC9fqyr2lZ8FM+2CQFE0qzb/54D883rCmKkawjDR1/UsQHUQG5C
-----END PRIVATE KEY-----

)EOF";
