#pragma once

// Otomatik uretilen ECC (secp256r1) SSL Sertifikasi ve Gizli Anahtari
// CN: insallah.com
// SAN: DNS:insallah.com, DNS:www.insallah.com, IP:192.168.4.1

const char SERVER_CERT_PEM[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIBtTCCAVygAwIBAgIUWAJk2B4ecbdXlYpp3SZ2mRf9gaMwCgYIKoZIzj0EAwIw
FzEVMBMGA1UEAwwMaW5zYWxsYWguY29tMB4XDTI2MTAwNjEzMTMzMFoXDTM2MTAw
MzEzMTMzMFowFzEVMBMGA1UEAwwMaW5zYWxsYWguY29tMFkwEwYHKoZIzj0CAQYI
KoZIzj0DAQcDQgAECXssyN3xKpNGl1ur11diPXg0+HuEoJJoOS7vISpoQSkhNuu1
T+iyzKZ9cAuww3mpNN7rp2d8BXrWQ0MhawWd/aOBhTCBgjAdBgNVHQ4EFgQUsGj2
h4wAg1rmOt+m+7294JhyQl0wHwYDVR0jBBgwFoAUsGj2h4wAg1rmOt+m+7294Jhy
Ql0wDwYDVR0TAQH/BAUwAwEB/zAvBgNVHREEKDAmggxpbnNhbGxhaC5jb22CEHd3
dy5pbnNhbGxhaC5jb22HBMCoBAEwCgYIKoZIzj0EAwIDRwAwRAIgdNSR6YmUzgxu
A3mdLAn9QVe3WkuGCYxldA1LbzB9aIECIGK+JBS8N45SbPG7+DjMQKe6WCds6GnS
OfR/fSgRGRgv
-----END CERTIFICATE-----

)EOF";

const char SERVER_KEY_PEM[] PROGMEM = R"EOF(
-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgJHyVgEKQnEhitkc8
VnxybimB8cSfHkF11ItGlB2nSYShRANCAAQJeyzI3fEqk0aXW6vXV2I9eDT4e4Sg
kmg5Lu8hKmhBKSE267VP6LLMpn1wC7DDeak03uunZ3wFetZDQyFrBZ39
-----END PRIVATE KEY-----

)EOF";
