#pragma once

// Apple iOS, Safari, Android ve Chrome ile 100% uyumlu ECC (secp256r1) SSL Sertifikasi
// Gecerlilik: 1 Yil (Apple max 398-825 gun kuralina tam uyumlu)
// SAN: DNS:insallah.com, DNS:www.insallah.com, DNS:esp32.local, IP:192.168.4.1
// EKU: TLS Web Server Authentication

const char SERVER_CERT_PEM[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIICDTCCAbKgAwIBAgIUcIphuhCuxSC3X+qH6hT0I9ukJpcwCgYIKoZIzj0EAwIw
QjEVMBMGA1UEAwwMaW5zYWxsYWguY29tMRwwGgYDVQQKDBNFU1AzMiBTZWN1cmUg
Um91dGVyMQswCQYDVQQGEwJUUjAeFw0yNjEwMDYyMDI5MjJaFw0yNzEwMDYyMDI5
MjJaMEIxFTATBgNVBAMMDGluc2FsbGFoLmNvbTEcMBoGA1UECgwTRVNQMzIgU2Vj
dXJlIFJvdXRlcjELMAkGA1UEBhMCVFIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AAQlYdlx0xO271yRtulp1/KHl0lU2iS68L5WmmdlO5G7rkMggQvd9srlV1grJOmN
sTr8QNQfEKDQj8e2UjFj/Xbpo4GFMIGCMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUE
DDAKBggrBgEFBQcDATA8BgNVHREENTAzggxpbnNhbGxhaC5jb22CEHd3dy5pbnNh
bGxhaC5jb22CC2VzcDMyLmxvY2FshwTAqAQBMB0GA1UdDgQWBBRPHJD2tx5ZdUwb
lUWnOXEoKgsJ0TAKBggqhkjOPQQDAgNJADBGAiEA6K423JbDnKhiIPMxmEgCGB3c
1ue782KDAIbtR4yRrtkCIQD5irqYc4mwFfhWUk9SszEs1LbPcXNv07nR1eDrPVSx
4Q==
-----END CERTIFICATE-----
)EOF";

const char SERVER_KEY_PEM[] PROGMEM = R"EOF(
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIEWQmq4MRaFF1p+x5VUer+bxgs543W2xnzrjyKWMNqYyoAoGCCqGSM49
AwEHoUQDQgAEJWHZcdMTtu9ckbbpadfyh5dJVNokuvC+VppnZTuRu65DIIEL3fbK
5VdYKyTpjbE6/EDUHxCg0I/HtlIxY/126Q==
-----END EC PRIVATE KEY-----
)EOF";
